parameter_config:
  src_index:
  - 2.3
  share_src_index: true
  src_index_range:
  - 1.0
  - 4.0
  diff_index: 2.5
  diff_index_range:
  - 1.0
  - 4.0
  L:
  - 6.0e+45
  share_L: true
  L_range:
  - 0
  - 1.0e+60
  src_dec:
  - 5.7
  src_ra:
  - 77.35
  Enorm: 100000.0
  Emin: 1e2
  Emax: 1e8
  Emin_src: 1.3365e2
  Emax_src: 1.3365e8
  Emin_diff: 1e2
  Emax_diff: 1e8
  diff_norm: 2.0e-13
  z:
  - 0.3365
  Emin_det_eq: true
  Emin_det: 2e2
  threads_per_chain: 2
  asimov: true
  atmospheric: false
  diffuse: false
  detector_model_type:
  - IC40
  - IC59
  - IC79
  - IC86_I
  - IC86_II
  obs_time:
  - 1.03041837
  - 0.96804266
  - 0.86528447
  - 0.91160313
  - 6.02031467
prior_config:
  src_index:
    name: NormalPrior
    mu: 2.0
    sigma: 1.5
  diff_index:
    name: NormalPrior
    mu: 2.52
    sigma: 0.09
  L:
    name: LogNormalPrior
    mu: 18.1e49
    sigma: 4.0
  diff_flux:
    name: LogNormalPrior
    mu: 5.4e-4
    sigma: 0.5
  atmo_flux:
    name: NormalPrior
    mu: 0.3
    sigma: 0.08
roi_config:
  roi_type: NorthernSkyROI
  size: 5.0
  apply_roi: true
