parameter_config:
  source_type: twice-broken-power-law
  fit_params:
  - src_index
  src_index:
  - 2.3
  beta_index:
  - 0.05
  beta_index_range:
  - -1.0
  - 1.0
  E0_src:
  - 1e5
  E0_src_range:
  - 1e3
  - 1e8
  share_src_index: true
  src_index_range:
  - 1.0
  - 4.0
  diff_index: 2.5
  diff_index_range:
  - 1.0
  - 4.0
  L:
  - 1.2e+47
  share_L: true
  L_range:
  - 0
  - 1.0e+60
  src_dec:
  - 5.7
  src_ra:
  - 77.35
  Enorm: 100000.0
  Emin: 1e2
  Emax: 1e9
  Emin_src: 1e2
  Emax_src: 1e9
  Emin_diff: 1e2
  Emax_diff: 1e9
  diff_norm: 2.0e-13
  z:
  - 0.3365
  Emin_det_eq: true
  Emin_det: 2e2
  MJD_min: 56917
  MJD_max: 57113
  frame: detector
  asimov: false
  atmospheric: true
  diffuse: true
stan_config:
  threads_per_chain: 40
  iterations: 1000
  iter_warmup: 1000
  seed: 1337
  chains: 1
prior_config:
  src_index:
    name: NormalPrior
    mu: 2.0
    sigma: 1.5
  beta_index:
    name: NormalPrior
    mu: 0.0
    sigma: 0.1
  E0_src:
    name: LogNormalPrior
    mu: 1e5
    sigma: 3
  diff_index:
    name: NormalPrior
    mu: 2.52
    sigma: 0.04
  L:
    name: LogNormalPrior
    mu: 18.1e49
    sigma: 4.0
  atmo_flux:
    name: NormalPrior
    mu: 0.3
    sigma: 0.08
roi_config:
  roi_type: CircularROI
  size: 5.0
  apply_roi: true
  DEC: 5.7
  RA: 77.35
ppc_config:
  n_samples: 10
  seed: 42
  directory: ppc
